In [1]:
from pathlib import Path

from telco_churn.data import load_raw_dataset

In [2]:
Path.cwd()

WindowsPath('c:/Users/v-jingwenh/codework/telco-customer-churn-pipeline/notebooks')

In [3]:
data_path = Path("../data/raw/Telco-Customer-Churn.csv")

if not data_path.exists():
    data_path = Path("data/raw/Telco-Customer-Churn.csv")

data = load_raw_dataset(data_path)

In [4]:
rows, columns = data.shape

print(f"Rows: {rows}")
print(f"Columns: {columns}")

Rows: 7043
Columns: 21

In [5]:
data.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

### 2. Column types and unique values

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   object
 1   gender            7043 non-null   object
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   object
 4   Dependents        7043 non-null   object
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   object
 7   MultipleLines     7043 non-null   object
 8   InternetService   7043 non-null   object
 9   OnlineSecurity    7043 non-null   object
 10  OnlineBackup      7043 non-null   object
 11  DeviceProtection  7043 non-null   object
 12  TechSupport       7043 non-null   object
 13  StreamingTV       7043 non-null   object
 14  StreamingMovies   7043 non-null   object
 15  Contract          7043 non-null   object
 16  PaperlessBilling  7043 non-null   object
 17  PaymentMethod     7043 non-null   object
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   object
 20  Churn             7043 non-null   object
dtypes: float64(1), int64(2), object(18)
memory usage: 1.1+ MB

In [7]:
column_summary = (
    data.dtypes
    .to_frame(name="dtype")
    .assign(unique_values=data.nunique(dropna=False))
    .sort_values("unique_values")
)

column_summary

                    dtype  unique_values
gender             object              2
SeniorCitizen       int64              2
Partner            object              2
Dependents         object              2
PhoneService       object              2
PaperlessBilling   object              2
Churn              object              2
MultipleLines      object              3
TechSupport        object              3
StreamingTV        object              3
OnlineBackup       object              3
DeviceProtection   object              3
StreamingMovies    object              3
Contract           object              3
OnlineSecurity     object              3
InternetService    object              3
PaymentMethod      object              4
tenure              int64             73
MonthlyCharges    float64           1585
TotalCharges       object           6531
customerID         object           7043

In [9]:
data[
    ["customerID", "SeniorCitizen", "tenure", "MonthlyCharges", "TotalCharges", "Churn"]
].dtypes

customerID         object
SeniorCitizen       int64
tenure              int64
MonthlyCharges    float64
TotalCharges       object
Churn              object
dtype: object